use std::path::PathBuf;
use std::sync::Arc;

use chrono::Utc;
use tokio::sync::Mutex;
use tokio_util::sync::CancellationToken;

use crate::knowledge::{
    find_tool_sequences, get_skill_candidate, insert_skill_candidate, list_skill_candidates,
    SkillCandidate, SkillCandidateStatus, ToolSequenceCandidate,
};
use crate::TeachdState;

/// Background loop: scans agent actions for repeated tool sequences every hour.
pub async fn skillgen_loop(state: Arc<Mutex<TeachdState>>, cancel: CancellationToken) {
    // Initial delay: wait 5 minutes before first scan to let data accumulate
    tokio::select! {
        _ = cancel.cancelled() => return,
        _ = tokio::time::sleep(tokio::time::Duration::from_secs(300)) => {}
    }

    let mut interval = tokio::time::interval(tokio::time::Duration::from_secs(3600));

    loop {
        tokio::select! {
            _ = cancel.cancelled() => {
                tracing::info!("skillgen loop shutting down");
                break;
            }
            _ = interval.tick() => {
                if let Err(e) = run_skillgen_cycle(&state).await {
                    tracing::warn!(error = %e, "skillgen cycle failed");
                }
            }
        }
    }
}

async fn run_skillgen_cycle(state: &Arc<Mutex<TeachdState>>) -> anyhow::Result<()> {
    let st = state.lock().await;

    // Find tool sequences appearing in 3+ distinct sessions
    let sequences = find_tool_sequences(&st.db, 3)?;
    if sequences.is_empty() {
        tracing::debug!("no repeated tool sequences found");
        return Ok(());
    }

    let mut new_candidates = 0;
    for seq in sequences.iter().take(10) {
        // Check if we already have a candidate for this tool sequence
        let candidate_id = format!("sc-{}", slug_from_tools(&seq.tools));
        if get_skill_candidate(&st.db, &candidate_id)?.is_some() {
            continue;
        }

        // Check dedup: skip if 80%+ overlap with an existing candidate
        let existing = list_skill_candidates(&st.db, None, 50)?;
        let dominated = existing.iter().any(|e| {
            tool_overlap(&seq.tools, &e.tools) >= 0.8
        });
        if dominated {
            continue;
        }

        let now = Utc::now();
        let confidence = compute_confidence(seq);
        let description = generate_description(&seq.tools);

        let candidate = SkillCandidate {
            id: candidate_id,
            name: skill_name_from_tools(&seq.tools),
            description,
            tools: seq.tools.clone(),
            session_count: seq.session_count,
            confidence,
            source_patterns: Vec::new(),
            status: SkillCandidateStatus::Pending,
            skill_path: None,
            created_at: now,
            updated_at: now,
        };

        insert_skill_candidate(&st.db, &candidate)?;
        new_candidates += 1;

        st.receipt_logger
            .log_event(
                "skill.candidate",
                &candidate.name,
                &format!(
                    "tools=[{}], sessions={}, confidence={:.2}",
                    candidate.tools.join(", "),
                    candidate.session_count,
                    candidate.confidence,
                ),
            )
            .await;
    }

    if new_candidates > 0 {
        tracing::info!(count = new_candidates, "new skill candidates detected");
    }

    Ok(())
}

/// Generate a SKILL.md file from a candidate.
pub fn generate_skill_md(candidate: &SkillCandidate) -> String {
    let tools_yaml: Vec<String> = candidate.tools.iter().map(|t| format!("  - {}", t)).collect();
    let now = Utc::now().format("%Y-%m-%d").to_string();

    let mut steps = String::new();
    for (i, tool) in candidate.tools.iter().enumerate() {
        steps.push_str(&format!(
            "{}. Execute `{}`:\n   ```\n   {}({{ /* parameters */ }})\n   ```\n\n",
            i + 1,
            tool,
            tool,
        ));
    }

    format!(
        r#"---
name: {}
description: >
  {}
  Auto-generated from {} observed sessions on {}.
tools:
{}
activation: manual
auto_generated: true
version: 1
confidence: {:.2}
---

# {}

{}

## Steps

{}## Notes

- This skill was auto-generated by teachd from repeated agent behavior.
- Review and customize the parameters before promoting to auto-activation.
- Confidence score: {:.0}% (based on {} sessions).
"#,
        candidate.name,
        candidate.description,
        candidate.session_count,
        now,
        tools_yaml.join("\n"),
        candidate.confidence,
        title_from_name(&candidate.name),
        candidate.description,
        steps,
        candidate.confidence * 100.0,
        candidate.session_count,
    )
}

/// Write a SKILL.md file to disk.
pub fn write_skill_file(state_dir: &str, candidate: &SkillCandidate) -> anyhow::Result<String> {
    // Reject path traversal: no slashes, backslashes, or ".." in candidate names
    if candidate.name.contains('/') || candidate.name.contains('\\') || candidate.name.contains("..") || candidate.name.is_empty() {
        anyhow::bail!("invalid skill candidate name: {}", candidate.name);
    }
    let safe_name = &candidate.name;

    let skill_dir = PathBuf::from(state_dir)
        .parent()
        .unwrap_or(&PathBuf::from("/var/lib/osmoda"))
        .join("skills")
        .join("auto")
        .join(&safe_name);

    std::fs::create_dir_all(&skill_dir)?;

    let skill_path = skill_dir.join("SKILL.md");
    let content = generate_skill_md(candidate);
    std::fs::write(&skill_path, &content)?;

    tracing::info!(
        skill = %candidate.name,
        path = %skill_path.display(),
        "wrote auto-generated SKILL.md"
    );

    Ok(skill_path.to_string_lossy().to_string())
}

// ── Helpers ──

fn slug_from_tools(tools: &[String]) -> String {
    let joined = tools.join("-");
    // Truncate to keep IDs reasonable
    if joined.len() > 60 {
        joined[..60].to_string()
    } else {
        joined
    }
}

fn skill_name_from_tools(tools: &[String]) -> String {
    // Create a readable name from the tool sequence
    let parts: Vec<&str> = tools.iter().map(|t| {
        // Strip common prefixes
        t.strip_prefix("system_").or_else(|| t.strip_prefix("service_"))
            .or_else(|| t.strip_prefix("shell_")).unwrap_or(t)
    }).collect();

    parts.join("-and-")
}

fn title_from_name(name: &str) -> String {
    name.replace('-', " ")
        .split_whitespace()
        .map(|w| {
            let mut c = w.chars();
            match c.next() {
                None => String::new(),
                Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
            }
        })
        .collect::<Vec<_>>()
        .join(" ")
}

fn generate_description(tools: &[String]) -> String {
    if tools.is_empty() {
        return "Auto-generated skill.".to_string();
    }

    let tool_list: Vec<&str> = tools.iter().map(|s| s.as_str()).collect();
    format!(
        "Automated procedure using {} in sequence.",
        tool_list.join(", then "),
    )
}

fn compute_confidence(seq: &ToolSequenceCandidate) -> f64 {
    // More sessions = higher confidence, capped at 1.0
    let session_factor = (seq.session_count as f64 / 8.0).min(1.0);
    // Shorter sequences are more reliable patterns
    let length_factor = (1.0 / (seq.tools.len() as f64 - 1.0).max(1.0)).min(1.0);
    // Combine: 70% session weight, 30% length weight
    (session_factor * 0.7 + length_factor * 0.3).min(1.0)
}

fn tool_overlap(a: &[String], b: &[String]) -> f64 {
    if a.is_empty() || b.is_empty() {
        return 0.0;
    }
    let a_set: std::collections::HashSet<&String> = a.iter().collect();
    let b_set: std::collections::HashSet<&String> = b.iter().collect();
    let intersection = a_set.intersection(&b_set).count();
    let union = a_set.union(&b_set).count();
    if union == 0 { 0.0 } else { intersection as f64 / union as f64 }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_slug_from_tools() {
        let tools = vec!["journal_logs".to_string(), "service_status".to_string(), "shell_exec".to_string()];
        let slug = slug_from_tools(&tools);
        assert_eq!(slug, "journal_logs-service_status-shell_exec");
    }

    #[test]
    fn test_skill_name_from_tools() {
        let tools = vec!["journal_logs".to_string(), "service_status".to_string(), "shell_exec".to_string()];
        let name = skill_name_from_tools(&tools);
        assert_eq!(name, "journal_logs-and-status-and-exec");
    }

    #[test]
    fn test_tool_overlap() {
        let a = vec!["foo".to_string(), "bar".to_string()];
        let b = vec!["bar".to_string(), "baz".to_string()];
        let overlap = tool_overlap(&a, &b);
        assert!((overlap - 1.0 / 3.0).abs() < 0.01);
    }

    #[test]
    fn test_tool_overlap_identical() {
        let a = vec!["foo".to_string(), "bar".to_string()];
        let overlap = tool_overlap(&a, &a);
        assert!((overlap - 1.0).abs() < 0.01);
    }

    #[test]
    fn test_compute_confidence() {
        let seq = ToolSequenceCandidate {
            tools: vec!["a".to_string(), "b".to_string(), "c".to_string()],
            session_count: 5,
            sessions: vec![],
            name: "test".to_string(),
        };
        let conf = compute_confidence(&seq);
        assert!(conf > 0.0 && conf <= 1.0);
    }

    #[test]
    fn test_write_skill_file_rejects_path_traversal() {
        let now = Utc::now();
        let candidate = SkillCandidate {
            id: "sc-evil".to_string(),
            name: "../../../etc/cron.d/evil".to_string(),
            description: "Malicious".to_string(),
            tools: vec!["shell_exec".to_string()],
            session_count: 3,
            confidence: 0.5,
            source_patterns: vec![],
            status: SkillCandidateStatus::Pending,
            skill_path: None,
            created_at: now,
            updated_at: now,
        };
        let result = write_skill_file("/tmp/test-teachd", &candidate);
        assert!(result.is_err(), "should reject path traversal in candidate name");
    }

    #[test]
    fn test_generate_skill_md() {
        let now = Utc::now();
        let candidate = SkillCandidate {
            id: "sc-test".to_string(),
            name: "check-and-restart".to_string(),
            description: "Check service status and restart if needed.".to_string(),
            tools: vec!["service_status".to_string(), "shell_exec".to_string()],
            session_count: 5,
            confidence: 0.85,
            source_patterns: vec![],
            status: SkillCandidateStatus::Pending,
            skill_path: None,
            created_at: now,
            updated_at: now,
        };

        let md = generate_skill_md(&candidate);
        assert!(md.contains("name: check-and-restart"));
        assert!(md.contains("auto_generated: true"));
        assert!(md.contains("activation: manual"));
        assert!(md.contains("service_status"));
        assert!(md.contains("shell_exec"));
    }
}
