# AgentOS Hetzner VPS — headless cloud deployment
#
# Deployment (tested approach — nixos-infect):
#   1. Create Hetzner Cloud server with Ubuntu 24.04
#   2. Add your SSH key in Hetzner dashboard (Security > SSH Keys)
#   3. SSH in: ssh -i .keys/agentos_hetzner root@<server-ip>
#   4. Run nixos-infect:
#      curl -sL https://raw.githubusercontent.com/elitak/nixos-infect/master/nixos-infect \
#        | NIX_CHANNEL=nixos-unstable PROVIDER=hetznercloud bash -x
#   5. Server reboots into NixOS
#   6. Enable flakes, sync repo, build:
#      # On the server:
#      rsync from local, then cargo build --release --workspace
#   7. Apply this config via nixos-rebuild switch
#
# Alternative (requires local Nix):
#   nix run github:nix-community/nixos-anywhere -- --flake .#agentos-hetzner root@<server-ip>
#
# Access:
#   ssh -i .keys/agentos_hetzner agent@<server-ip>
#   ssh -i .keys/agentos_hetzner -L 18789:localhost:18789 agent@<server-ip>
#   Then open localhost:18789 in browser
#
# IMPORTANT: After nixos-infect, the boot loader is GRUB (not systemd-boot).
# The hardware-configuration.nix generated by nixos-infect takes precedence.
#
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  # --- System Identity ---
  networking.hostName = "agentos-cloud";
  system.stateVersion = "24.11";

  # --- Enable AgentOS ---
  services.agentos = {
    enable = true;
    openclaw.enable = true;
    sandbox.enable = true;
    memory.enable = true;
  };

  # --- Disk Layout (disko — for nixos-anywhere deployments) ---
  # If using nixos-infect, this is ignored (infect keeps existing partitions)
  disko.devices = {
    disk.main = {
      type = "disk";
      device = "/dev/sda";
      content = {
        type = "gpt";
        partitions = {
          ESP = {
            size = "512M";
            type = "EF00";
            content = {
              type = "filesystem";
              format = "vfat";
              mountpoint = "/boot";
              mountOptions = [ "umask=0077" ];
            };
          };
          root = {
            size = "100%";
            content = {
              type = "filesystem";
              format = "ext4";
              mountpoint = "/";
            };
          };
        };
      };
    };
  };

  # --- Boot ---
  # Hetzner Cloud VPS uses EFI + GRUB (not systemd-boot)
  # nixos-infect sets up GRUB in hardware-configuration.nix
  # For nixos-anywhere: use systemd-boot
  boot.loader.systemd-boot.enable = lib.mkDefault true;
  boot.loader.efi.canTouchEfiVariables = lib.mkDefault true;
  boot.initrd.availableKernelModules = [ "ata_piix" "uhci_hcd" "virtio_pci" "virtio_scsi" "sd_mod" "sr_mod" "xen_blkfront" "vmw_pvscsi" ];
  boot.initrd.kernelModules = [ "nvme" ];

  # --- Networking ---
  networking = {
    useDHCP = true;
    firewall = {
      enable = true;
      allowedTCPPorts = [ 22 ];
      # Gateway (18789) is localhost-only — access via SSH tunnel
    };
  };

  # --- User ---
  users.users.agent = {
    isNormalUser = true;
    description = "AgentOS Admin";
    extraGroups = [ "wheel" ];
    openssh.authorizedKeys.keys = [
      # Replace with your SSH public key:
      #   ssh-keygen -t ed25519 -f .keys/agentos_hetzner -N ""
      #   cat .keys/agentos_hetzner.pub
      "ssh-ed25519 AAAA_YOUR_PUBLIC_KEY_HERE agentos-hetzner"
    ];
  };

  security.sudo.wheelNeedsPassword = false;

  # --- SSH ---
  services.openssh = {
    enable = true;
    settings = {
      PasswordAuthentication = false;
      PermitRootLogin = "prohibit-password";
      X11Forwarding = false;
    };
  };

  users.users.root.openssh.authorizedKeys.keys = [
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMRfgoK7tKkPUX49Et2CwJDIX7QHocySALiuTV2+3bHf agentos-hetzner"
  ];

  # --- Nix ---
  nix.settings = {
    experimental-features = [ "nix-command" "flakes" ];
    auto-optimise-store = true;
  };

  nix.gc = {
    automatic = true;
    dates = "weekly";
    options = "--delete-older-than 14d";
  };

  # --- Swap (recommended for small VPS) ---
  swapDevices = [{
    device = "/swapfile";
    size = 2048; # 2GB
  }];

  # --- Misc ---
  time.timeZone = "UTC";
  i18n.defaultLocale = "en_US.UTF-8";

  environment.systemPackages = with pkgs; [
    vim
    tmux
    htop
    git
    curl
    jq
    ripgrep
    fd
    # Build toolchain — required for compiling Rust crates on the server
    # (cc linker for proc-macros, pkg-config for sqlite/openssl native deps)
    gcc
    gnumake
    pkg-config
    sqlite
    openssl
    rustc
    cargo
    nodejs_22
  ];
}
